# Generated by Django 3.2.9 on 2021-11-05 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_status', models.IntegerField(default=0)),
                ('incoming_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_user_id', to=settings.AUTH_USER_MODEL)),
                ('outgoing_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
