# Generated by Django 3.2.9 on 2021-11-06 07:11

from django.db import migrations, models
import interestsProfile.models


class Migration(migrations.Migration):

    dependencies = [
        ('interestsProfile', '0004_alter_algoidtouserid_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algoidtouserid',
            name='mapping',
            field=models.JSONField(default=interestsProfile.models.returnEmptyDict),
        ),
    ]
